import { useState } from 'react';
import Head from 'next/head'
import SearchInput from '../components/SearchInput';
import CountriesTable from '../components/CountriesTable';
import CircularProgress from '@material-ui/core/CircularProgress';

export default function Home() {
  const [countries, setCountries] = useState([]);
  const [loading, setLoading] = useState(false);
  const [statusCode, setStatusCode] = useState(false);
  
  const handleSearch = async (query) => {
    setLoading(true);

    try {
      const response = await fetch(`/api/countries?q=${query}`);
      const data = await response.json();
      setStatusCode(response.status);
      setCountries(data);
    } catch (error) {
      console.error("Error fetching data:", error);
    }

    setLoading(false);
  }

  return (
    <>
      <Head>
        <title>Countries App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h2 style={{ textAlign: "center" }}>Countries App</h2>
        <SearchInput onSearch={handleSearch} />

        {loading && (
          <div style={{ display: 'flex', justifyContent: 'center', marginTop: '20px' }}>
            <CircularProgress />
          </div>
        )}

        {statusCode === 400 ? (
          <h3 style={{ textAlign: "center" }}>No se encontraron resultados.</h3>
        ) : (
          countries.length !== 0 && <CountriesTable countries={countries} />
        )}
      </main>
    </>
  )
}
